[Mouse & Keyboard]
DPAD_UP=W
DPAD_DOWN=S
DPAD_LEFT=A
DPAD_RIGHT=D
BUTTON_UP=LSHIFT
BUTTON_DOWN=SPACE
BUTTON_LEFT=Q
BUTTON_RIGHT=E
BUTTON_START=ESCAPE
BUTTON_SELECT=RETURN
BUTTON_LSHOULDER=TAB
BUTTON_RSHOULDER=R

[Controller]
# I believe only Nintendo Switch Pro controller is supported for now
DPAD_UP=DPAD_UP
DPAD_DOWN=DPAD_DOWN
DPAD_LEFT=DPAD_LEFT
DPAD_RIGHT=DPAD_RIGHT
BUTTON_UP=X
BUTTON_DOWN=B
BUTTON_LEFT=Y
BUTTON_RIGHT=A
BUTTON_START=START
BUTTON_SELECT=BACK
BUTTON_LSHOULDER=LEFTSHOULDER
BUTTON_RSHOULDER=RIGHTSHOULDER